#!/usr/bin/env node
// Recompute the named exit cohorts against the LIVE Paseo validator set and
// rewrite plan/providers.toml + plan/downsizing-plan.local.toml [exit_cohort].
// Run this shortly before go-live so the announced cohorts reflect the current
// set. Deterministic (no LLM). Needs @polkadot/api (see tools/package.json).
//
//   node tools/refresh-cohorts.mjs [--relay wss://...] [--submission /path/to/paseo-action-submission]
import { ApiPromise, WsProvider } from '@polkadot/api';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const arg = (k, d) => { const i = process.argv.indexOf(k); return i >= 0 ? process.argv[i + 1] : d; };
const RELAY = arg('--relay', 'wss://paseo-rpc.n.dwellir.com');
const SUB = arg('--submission', '/home/alemart/Projects/paseo-network/paseo-action-submission');
const TARGETS = [100, 60, 40, 20];      // step validator targets (match the plan)
const CYCLE_AT = ['2026-07-02T18:00:00+02:00','2026-07-03T00:00:00+02:00','2026-07-03T06:00:00+02:00','2026-07-03T12:00:00+02:00'];
const IBP8 = new Set(['amforc','dwellir','gatotech','metaspan','radiumblock','rotko','stakeplus','turboflakes']);
const RECENTLY_CUT = new Set(['luckyfriday','polkadotters','stkd']);

// --- read provider YAMLs: stash -> {provider, valname}; provider -> {display,matrix,ibp} ---
const ACTIVE_DIR = path.join(SUB, 'paseo-validators/active');
const stashInfo = {}, provMeta = {};
for (const f of fs.readdirSync(ACTIVE_DIR)) {
  if (!f.endsWith('.yml') || f === 'example.yml') continue;
  const name = f.slice(0, -4);
  const t = fs.readFileSync(path.join(ACTIVE_DIR, f), 'utf8');
  const riot = (t.match(/riot:\s*"?([^"\n]+)"?/) || [])[1] || '';
  const disp = (t.match(/identity:\s*\n\s*display:\s*"?([^"\n]+)"?/) || [])[1] || name;
  const ibp = IBP8.has(name) ? 'ibp8' : RECENTLY_CUT.has(name) ? 'recently-cut' : 'non-ibp';
  provMeta[name] = { display: disp.trim().replace(/"/g,''), matrix: riot.trim(), ibp };
  const re = /display:\s*"?([^"\n]+)"?\s*\n\s*stash:\s*(\w+)/g; let m;
  while ((m = re.exec(t))) stashInfo[m[2]] = { provider: name, valname: m[1].trim().replace(/"/g,'') };
}

const tier = (prov) => prov == null ? 0 : IBP8.has(prov) ? 3 : RECENTLY_CUT.has(prov) ? 1 : 2;

const api = await ApiPromise.create({ provider: new WsProvider(RELAY), noInitWarn: true });
const active = (await api.query.session.validators()).toJSON();
await api.disconnect();

// order: leave-first (tier asc), then provider name, then validator name; last-20 = floor
const ordered = active.map(stash => {
  const info = stashInfo[stash] || { provider: null, valname: 'unattributed' };
  return { stash, ...info };
}).sort((a, b) =>
  tier(a.provider) - tier(b.provider) ||
  String(a.provider).localeCompare(String(b.provider)) ||
  a.valname.localeCompare(b.valname));

const N = ordered.length;
const floorCount = TARGETS[TARGETS.length - 1];              // 20
// Floor: keep ~2-3 validators from EACH IBP-8 provider (spread, so no core
// member is fully removed), totalling floorCount. Round-robin the keeps.
const ibpVals = {};
ordered.filter(v => tier(v.provider) === 3).forEach(v => (ibpVals[v.provider] ??= []).push(v));
const ibpProvs = Object.keys(ibpVals).sort((a, b) => ibpVals[b].length - ibpVals[a].length);
const keepN = Object.fromEntries(ibpProvs.map(p => [p, 0]));
for (let assigned = 0; assigned < floorCount; ) {
  let progress = false;
  for (const p of ibpProvs) {
    if (assigned >= floorCount) break;
    if (keepN[p] < ibpVals[p].length) { keepN[p]++; assigned++; progress = true; }
  }
  if (!progress) break;
}
const floorSet = new Set();
for (const p of ibpProvs) ibpVals[p].slice(ibpVals[p].length - keepN[p]).forEach(v => floorSet.add(v.stash));
const leaving = ordered.filter(v => !floorSet.has(v.stash));
const floor = ordered.filter(v => floorSet.has(v.stash));
// assign leaving to cycles by target: cycle i removes (running - target)
let running = N, idx = 0; const cycleOf = {};
TARGETS.forEach((target, i) => {
  const take = Math.max(0, running - target);
  for (let k = 0; k < take && idx < leaving.length; k++, idx++) cycleOf[leaving[idx].stash] = i + 1;
  running = target;
});
floor.forEach(v => cycleOf[v.stash] = 'floor');

// --- write providers.toml ---
const byProv = {};
for (const v of ordered) { (byProv[v.provider ?? '(unattributed)'] ??= []).push(v); }
let ptoml = `# Compiled Paseo exit schedule — GENERATED by tools/refresh-cohorts.mjs against\n# the LIVE set (${N} validators). LOCAL/gitignored — deployed via scp.\n[meta]\nmatrix_room = "#polkadot-community-testnet:parity.io"\nshutdown = "2026-07-04T12:00:00+02:00"\n` +
  CYCLE_AT.map((d,i)=>`cycle_${i+1} = "${d}"`).join('\n') + '\n';
for (const prov of Object.keys(byProv)) {
  const md = provMeta[prov] || { display: prov, matrix: '', ibp: 'non-ibp' };
  ptoml += `\n[[provider]]\nname = "${prov}"\ndisplay = "${md.display}"\nmatrix = "${md.matrix}"\nibp = "${md.ibp}"\n`;
  for (const v of byProv[prov]) ptoml += `[[provider.validator]]\nname = "${v.valname}"\nstash = "${v.stash}"\ncycle = "${cycleOf[v.stash]}"\n`;
}
fs.writeFileSync(path.join(ROOT, 'plan/providers.toml'), ptoml);

// --- write downsizing-plan.local.toml (copy committed plan, inject exit_cohort) ---
let plan = fs.readFileSync(path.join(ROOT, 'plan/downsizing-plan.toml'), 'utf8');
let block = '';
[1,2,3,4].forEach(c => { const ss = leaving.filter(v => cycleOf[v.stash] === c).map(v => v.stash);
  block += `step_${c} = [\n` + ss.map(s => `  "${s}",`).join('\n') + '\n]\n'; });
plan = plan.replace(/step_1 = \[\]\nstep_2 = \[\]\nstep_3 = \[\]\nstep_4 = \[\]/, block.trimEnd());
fs.writeFileSync(path.join(ROOT, 'plan/downsizing-plan.local.toml'), plan);

// --- summary ---
const counts = {1:0,2:0,3:0,4:0}; leaving.forEach(v => counts[cycleOf[v.stash]]++);
console.log(`live set: ${N} validators`);
[1,2,3,4].forEach(c => console.log(`  cycle ${c} (${CYCLE_AT[c-1].slice(5,16)}): ${counts[c]} leaving`));
console.log(`  floor (survive): ${floor.length}  [${[...new Set(floor.map(v=>v.provider))].join(', ')}]`);
const unmatched = active.filter(s => !stashInfo[s]).length;
console.log(`  active not in any provider YAML: ${unmatched}`);
console.log('wrote plan/providers.toml + plan/downsizing-plan.local.toml');
